### ISSUE TITLE
Taxa de mortalidade

### ISSUE THREAD

**Issue by matheusarauj** [juliobguedes/covid#1]
Olá. Achei interessante o projeto, e uma feature que acredito que seria bastante interessante seria a de taxa de mortalidade ao longo do tempo. Este indicativo poderia ilustrar como os países estão lidando com o surto ao longo do mesmo.

**Comment by juliobguedes** [comment]
Oi @matheusarauj, obrigado pela ideia! No caso, a taxa de mortalidade vai mudando também a cada dia? Ou ela deveria permanecer estática para cada país/mundo?

**Comment by joseims** [comment]
Acho que ela poderia ir mudar de acordo com os dados (dia e pais), sendo ela simplesmente o óbitos/casos. Embora acho que só faça sentido ver a taxa de mortalidade na parte dos gráficos e não da do mapa mundo, acho que em um gráfico de pontos ficaria top.
