### ISSUE TITLE
Fix the scales between the 3 charts

### ISSUE THREAD

**Issue by joseims** [juliobguedes/covid#7]
Sometimes the scale between the confirmed cases and death's are on extremely different scales. It gives the false impression that the death's are higher than they actually are

**Comment by juliobguedes** [comment]
Since COVID-19 lethality is around 2%, creating a chart that only goes to 2% of the y-scale makes it hard to read and understand. How to overcome this problem? Logarithmic scales might also be hard to understand

**Comment by juliobguedes** [comment]
This issue will be continued in #15.
